chorerate/routes/auth.py
from flask import render_template, request, redirect, \
                  url_for, flash, session, Blueprint
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from chorerate import db

# Models
from chorerate.models.user import User

from chorerate.helpers.household_helpers import add_user_to_household_by_token

bp = Blueprint('auth', __name__)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        token = session.pop('registration_token', None)

        username = request.form['username']
        password = request.form['password']
        confirm_password = request.form['confirm-password']

        if password != confirm_password:
            flash('Passwords do not match.', 'danger')
            return render_template('auth/register.html', username=username)

        hashed_password = generate_password_hash(
            password, method='pbkdf2:sha256')
        new_user = User(username=username, password=hashed_password)
        existing_user = User.query.filter_by(
            username=new_user.username).first()

        if not existing_user:
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)

            if token:
                return add_user_to_household_by_token(new_user, token)
            else:
                flash(f"Welcome {new_user.username}!", 'success')
            return redirect(url_for('home.homepage')) 
        else:
            flash('Username already exists.', 'danger')

    token = request.args.get('token')

    if token:
        if current_user.is_authenticated:
            return add_user_to_household_by_token(current_user, token)

        session['registration_token'] = token

    return render_template('auth/register.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    '''Login route, redirect to homepage'''
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                flash(f"Welcome {user.username}!", 'success')
                login_user(user)

                return redirect(url_for('home.homepage'))
            else:
                flash('Incorrect password.', 'danger')
        else:
            flash('User does not exist.', 'danger')

        return redirect(url_for('auth.login'))
    return render_template('auth/login.html')


@bp.route('/logout')
@login_required
def logout():
    '''Logout route, redirects to login'''
    flash("You have been logged out", 'info')
    logout_user()
    return redirect(url_for('auth.login'))

chorerate/routes/chores.py
from flask import Blueprint, render_template, request, \
    redirect, url_for, flash, jsonify
from flask_login import login_required
from datetime import datetime
from chorerate import db

# Models
from chorerate.models.chore import Chore
from chorerate.models.allocated_chore import AllocatedChore
from chorerate.models.chore_rating import ChoreRating
from chorerate.models import FrequencyEnum

from chorerate.helpers import household_helpers as household_helper
from chorerate.helpers import chore_helpers as chore_helper
import json

bp = Blueprint('chore', __name__)


@bp.route('/rate', methods=['GET', 'POST'])
@login_required
def rate():
    '''View for the rate page'''
    current_member = household_helper.current_household_member()

    if request.method == 'POST':
        data = json.loads(request.data.decode('utf-8'))
        rating, chord_id = map(int, data.values())

        existing_rating = db.session.query(ChoreRating).filter_by(
            household_member_id=current_member.id, chore_id=chord_id).first()

        if existing_rating:
            existing_rating.rating = rating
        else:
            new_rating = ChoreRating(
                household_member_id=current_member.id,
                chore_id=chord_id,
                rating=rating)

            db.session.add(new_rating)
        db.session.commit()

        return jsonify({'message': 'success'})

    household_member = household_helper.current_household_member()
    unrated_chores = chore_helper\
        .get_unrated_chores_for_member(household_member)

    household = household_helper.current_household()

    # If all chores have been rated, redirect to edit ratings
    # Unless there are no chores in the household.
    if len(unrated_chores) == 0 and not len(household.chores) == 0:
        rated_chores_rows = db.session.query(Chore, ChoreRating).join(
            ChoreRating).filter(
                ChoreRating.household_member_id == current_member.id).all()

        rated_chores = [{'id': chore.id,
                         'name': chore.name,
                         'rating': rating.rating,
                         'duration_minutes': chore.duration_minutes}
                        for chore, rating in rated_chores_rows]

        rated_chores.sort(key=lambda x: x['name'])
        return render_template('chores/edit-ratings.html',
                               rated_chores=rated_chores)

    # If has chores and there are unrated chores, render the rate page
    has_chores = len(household.chores) > 0
    return render_template('chores/rate-chores.html', has_chores=has_chores)


@bp.route('/rate/get-unrated')
@login_required
def get_unrated():
    '''Get unrated chores for the current user for the rate chores page'''
    household_member = household_helper.current_household_member()
    unrated = chore_helper.get_unrated_chores_for_member(household_member)
    return jsonify([{'id': chore.id,
                     'name': chore.name,
                     'frequency': chore.frequency.value,
                     'times_per_frequency': chore.times_per_frequency}
                    for chore in unrated])


@bp.route('/toggle-chore-completed', methods=['POST'])
@login_required
def toggle_completed():
    '''Toggle the completion status of a chore'''
    data = request.get_json()
    chore_id = data['chore_id']

    member = household_helper.current_household_member()

    chore = Chore.query.get(chore_id)
    allocation = AllocatedChore.query.filter_by(chore_id=chore_id,
                                                household_member_id=member.id).first()
    if not allocation:
        flash(f"{chore.name} is not your chore.", 'error')
        return redirect(url_for('home.homepage'))
    else:
        if chore.date_completed and chore.date_completed == datetime.now().date():
            chore.date_completed = None
        else:
            chore.date_completed = datetime.now().date()
        db.session.commit()
        return jsonify({'message': 'success',
                        'completed': chore.date_completed == datetime.now().date()})


@bp.route('/manage', methods=['GET', 'POST'])
@login_required
def manage():
    '''Add chores and view all chores to edit'''
    if request.method == 'POST':
        name = request.form['chore-name']
        frequency = request.form['chore-frequency']
        frequency_enum = FrequencyEnum(frequency)
        times_per_frequency = request.form['chore-times']
        duration_minutes = request.form['chore-duration']
        household_id = household_helper.current_household().id
        new_chore = Chore(household_id=household_id,
                          name=name,
                          frequency=frequency_enum,
                          times_per_frequency=times_per_frequency,
                          duration_minutes=duration_minutes)
        db.session.add(new_chore)
        db.session.commit()
        flash(f"Chore #{new_chore.id} - '{name.lower()}' \
            added successfully!", 'success')
        return redirect(url_for('chore.manage'))
    household_id = household_helper.current_household().id
    chores = Chore.query.filter_by(household_id=household_id).all()
    member_id = household_helper.current_household_member().id
    allocations = AllocatedChore.query.filter_by(
        household_member_id=member_id).all()
    return render_template('chores/manage.html',
                           chores=chores,
                           allocations=allocations)


@bp.route('/manage/edit-chore/<int:chore_id>', methods=['GET', 'POST'])
@login_required
def edit_chore(chore_id):
    if request.method == 'POST':
        chore_id = request.form['chore-id']
        chore = Chore.query.get(chore_id)
        chore.name = request.form['chore-name']
        chore.frequency = FrequencyEnum(request.form['chore-frequency'])
        chore.times_per_frequency = request.form['chore-times']
        chore.duration_minutes = request.form['chore-duration']

        allocation_member_id = request.form['allocation']

        if allocation_member_id:
            allocated_user = AllocatedChore.query.filter_by(
                chore_id=chore_id).first()

            if not allocated_user:
                allocated_user = AllocatedChore(
                    household_member_id=allocation_member_id,
                    chore_id=chore_id,
                    due_date=datetime.now().date())  # Remove later
                db.session.add(allocated_user)

            allocated_user.household_member_id = allocation_member_id

        db.session.commit()
        flash(f"Chore #{chore_id} - '{chore.name.lower()}' \
            updated successfully!", 'success')
        return redirect(url_for('chore.manage'))

    chore = Chore.query.get(chore_id)
    members = household_helper.current_household().members
    return render_template('chores/edit-chore.html',
                           chore=chore,
                           members=members)


@bp.route('/manage/delete-chore/<int:chore_id>', methods=['GET', 'POST'])
@login_required
def delete_chore(chore_id):
    chore = Chore.query.get(chore_id)

    users_household = household_helper.current_household()

    if chore.household_id != users_household.id:
        flash("You do not have permission to delete this chore.", 'danger')
        return redirect(url_for('home.homepage'))

    if request.method == 'POST':
        db.session.delete(chore)
        db.session.commit()
        flash(f"Chore #{chore_id} - '{chore.name.lower()}' \
            deleted successfully!", 'success')
        return redirect(url_for('chore.manage'))

    return render_template('chores/delete-chore.html', chore=chore)

chorerate/templates/base.html
<!DOCTYPE html>
<html lang="en-gb">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
        {% block css %}{% endblock %}
        <title>{% block title %}ChoreRate{% endblock %}</title>
    </head>

    <body>
        <nav>
            <div id="navbar">
                <div class="container">
                    <div id="nav-container">
                        <div id="logo">
                            <a href="{{ url_for('home.homepage') }}">
                                <img width="60" height="30" src="{{ url_for('static', filename='images/logo.webp') }}" alt="">
                            </a>
                        </div>
                        {% if current_user.is_authenticated %}
                        <div id="nav-link-container">
                            <a class="nav-link" href="{{ url_for('chore.rate') }}">Rate Chores</a>
                            <div class="dropdown">
                                <button class="dropdown-btn">Household</button>
                                <div class="dropdown-content-container">
                                    <div class="dropdown-content">
                                        <a class="nav-link" href="{{ url_for('chore.manage') }}">Manage chores</a>
                                        <a class="nav-link" href="{{ url_for('household.manage_members') }}">Members</a>
                                    </div>
                                </div>
                            </div>
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <div id="flashes-container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                <ul id="flashes" class="">
                    {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            {% endwith %}
        </div>

        <main>
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </main>

        {% block scripts %}{% endblock %}
    </body>

</html>

chorerate/templates/index.html
{% extends "base.html" %}

{% block content %}
    <section>
        <h2>Today's Chores</h2>
        {% if not todays_chores %}
            <p>No chores today!</p>
        {% else %}
            <ul class="chore-list" id="todays-chores">
                {% for chore in todays_chores %}
                <li class="{% if chore.is_overdue and not chore.is_completed %}overdue{% endif %}
                           {% if chore.is_completed() %}completed{% endif %}"
                    data-chore-id="{{ chore.id }}"
                >
                    <span><strong>Chore: </strong>{{ chore.name }}</span>
                    <span>
                        <strong>Duration: </strong>
                         {{ chore.duration_minutes }} minutes
                    </span>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    </section>

    <br>
    <hr>

    <section>
        <h2>Your chores</h2>
        {% if not chores %}
            <p>Pending chore allocation...</p>
        {% else %}
        <table class="chore-table">
            <tr>
                <th>Chore</th>
                <th>Frequency</th>
                <th>Next due</th>
            </tr>
            {% for chore in chores %}
            <tr>
                <td>
                    {{ chore.name }}
                </td>
                <td>
                    {{ chore.times_per_frequency }}x
                    {% if chore.frequency.value == 'daily' %}
                    per day
                    {% elif chore.frequency.value == 'weekly' %}
                    per week
                    {% elif chore.frequency.value == 'monthly' %}
                    per month
                    {% endif %}
    
                    {{ chore.duration_minutes }} minutes
                </td>
                <td>
                    {{ chore.get_next_due().strftime('%d %B %Y') }}
                </td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </section>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/toggle-chore-completed.js') }}"></script>
{% endblock %}

chorerate/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div id="page-header">
        <h1>Login</h1>
    </div>

    <form class="form form--sm" method="POST">
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username">
        </div class="form-group">

        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password">
        </div>

        <button class="btn form--btn" type="submit">Login</button>

        <a href="{{ url_for('register') }}" class="small-link">Click here to register</a>
    </form>
</div>
    
{% endblock %}