chorerate/models/chore.py
from datetime import datetime, timedelta

from chorerate import db
from sqlalchemy import Enum
from . import FrequencyEnum

import math


class Chore(db.Model):
    '''Model for the chore table'''
    __tablename__ = 'chores'
    id = db.Column(db.Integer, primary_key=True)
    household_id = db.Column(db.Integer,
                             db.ForeignKey('households.id'),
                             nullable=False)
    name = db.Column(db.String(50), nullable=False)
    frequency = db.Column(Enum(FrequencyEnum), nullable=False)
    times_per_frequency = db.Column(db.SmallInteger, nullable=False)
    duration_minutes = db.Column(db.SmallInteger, nullable=False)
    last_scheduled = db.Column(db.Date, nullable=True)
    date_completed = db.Column(db.Date, nullable=True)

    allocation = db.relationship('AllocatedChore',
                                 backref='chore',
                                 uselist=False)

    def num_scheduled_since_allocation(self, last_ran_chore_allocation):
        '''
            Returns the number of times the chore has been scheduled since the
            last chore allocation was run
        '''

        if last_ran_chore_allocation is None:
            return 0
        match (self.frequency):
            case FrequencyEnum.DAILY:
                return (datetime.now().date()
                        - last_ran_chore_allocation).days
            case FrequencyEnum.WEEKLY:
                return (datetime.now().date()
                        - last_ran_chore_allocation).days // 7
            case FrequencyEnum.MONTHLY:
                return (datetime.now().date()
                        - last_ran_chore_allocation).days // 28

    def initialize_last_scheduled(self):
        if self.last_scheduled is None:
            self.set_last_scheduled_today()
            self.last_scheduled = self.get_next_due()

    def get_next_due(self):
        today = datetime.now().date()
        match (self.frequency):
            case FrequencyEnum.DAILY:
                return max(self.last_scheduled + timedelta(days=1), today)
            case FrequencyEnum.WEEKLY:
                days = math.round(7 / self.times_per_frequency)
                return max(self.last_scheduled + timedelta(days=days), today)
            case FrequencyEnum.MONTHLY:
                days = math.round(28 / self.times_per_frequency)
                return max(self.last_scheduled + timedelta(days=days), today)

    def is_completed(self):
        if self.date_completed is None:
            return False
        return self.date_completed == datetime.now().date()

    def is_overdue(self):
        return self.get_next_due() < datetime.now().date()

    def set_last_scheduled_today(self):
        self.last_scheduled = datetime.now().date()

    def __repr__(self):
        return f"<{self.name} {self.frequency} - {self.times_per_frequency}x>"

chorerate/routes/chores.py
from flask import Blueprint, render_template, request, \
    redirect, url_for, flash, jsonify
from flask_login import login_required
from datetime import datetime
from chorerate import db

# Models
from chorerate.models.chore import Chore
from chorerate.models.allocated_chore import AllocatedChore
from chorerate.models.chore_rating import ChoreRating
from chorerate.models import FrequencyEnum

from chorerate.helpers import household_helpers as household_helper
from chorerate.helpers import chore_helpers as chore_helper
import json

bp = Blueprint('chore', __name__)


@bp.route('/rate', methods=['GET', 'POST'])
@login_required
def rate():
    '''View for the rate page'''
    current_member = household_helper.current_household_member()

    if request.method == 'POST':
        data = json.loads(request.data.decode('utf-8'))
        rating, chord_id = map(int, data.values())

        existing_rating = db.session.query(ChoreRating).filter_by(
            household_member_id=current_member.id, chore_id=chord_id).first()

        if existing_rating:
            existing_rating.rating = rating
        else:
            new_rating = ChoreRating(
                household_member_id=current_member.id,
                chore_id=chord_id,
                rating=rating)

            db.session.add(new_rating)
        db.session.commit()

        return jsonify({'message': 'success'})

    household_member = household_helper.current_household_member()
    unrated_chores = chore_helper\
        .get_unrated_chores_for_member(household_member)

    household = household_helper.current_household()

    # If all chores have been rated, redirect to edit ratings
    # Unless there are no chores in the household.
    if len(unrated_chores) == 0 and not len(household.chores) == 0:
        rated_chores_rows = db.session.query(Chore, ChoreRating).join(
            ChoreRating).filter(
                ChoreRating.household_member_id == current_member.id).all()

        rated_chores = [{'id': chore.id,
                         'name': chore.name,
                         'rating': rating.rating,
                         'duration_minutes': chore.duration_minutes}
                        for chore, rating in rated_chores_rows]

        rated_chores.sort(key=lambda x: x['name'])
        return render_template('chores/edit-ratings.html',
                               rated_chores=rated_chores)

    # If has chores and there are unrated chores, render the rate page
    has_chores = len(household.chores) > 0
    return render_template('chores/rate-chores.html', has_chores=has_chores)


@bp.route('/rate/get-unrated')
@login_required
def get_unrated():
    '''Get unrated chores for the current user for the rate chores page'''
    household_member = household_helper.current_household_member()
    unrated = chore_helper.get_unrated_chores_for_member(household_member)
    return jsonify([{'id': chore.id,
                     'name': chore.name,
                     'frequency': chore.frequency.value,
                     'times_per_frequency': chore.times_per_frequency}
                    for chore in unrated])


@bp.route('/toggle-chore-completed', methods=['POST'])
@login_required
def toggle_completed():
    '''Toggle the completion status of a chore'''
    data = request.get_json()
    chore_id = data['chore_id']

    member = household_helper.current_household_member()

    chore = Chore.query.get(chore_id)
    allocation = AllocatedChore.query.filter_by(chore_id=chore_id,
                                                household_member_id=member.id).first()
    if not allocation:
        flash(f"{chore.name} is not your chore.", 'error')
        return redirect(url_for('home.homepage'))
    else:
        if chore.date_completed and chore.date_completed == datetime.now().date():
            chore.date_completed = None
        else:
            chore.date_completed = datetime.now().date()
        db.session.commit()
        return jsonify({'message': 'success',
                        'completed': chore.date_completed == datetime.now().date()})


@bp.route('/manage', methods=['GET', 'POST'])
@login_required
def manage():
    '''Add chores and view all chores to edit'''
    if request.method == 'POST':
        name = request.form['chore-name']
        frequency = request.form['chore-frequency']
        frequency_enum = FrequencyEnum(frequency)
        times_per_frequency = request.form['chore-times']
        duration_minutes = request.form['chore-duration']
        household_id = household_helper.current_household().id
        new_chore = Chore(household_id=household_id,
                          name=name,
                          frequency=frequency_enum,
                          times_per_frequency=times_per_frequency,
                          duration_minutes=duration_minutes)
        db.session.add(new_chore)
        db.session.commit()
        flash(f"Chore #{new_chore.id} - '{name.lower()}' \
            added successfully!", 'success')
        return redirect(url_for('chore.manage'))
    household_id = household_helper.current_household().id
    chores = Chore.query.filter_by(household_id=household_id).all()
    member_id = household_helper.current_household_member().id
    allocations = AllocatedChore.query.filter_by(
        household_member_id=member_id).all()
    return render_template('chores/manage.html',
                           chores=chores,
                           allocations=allocations)


@bp.route('/manage/edit-chore/<int:chore_id>', methods=['GET', 'POST'])
@login_required
def edit_chore(chore_id):
    if request.method == 'POST':
        chore_id = request.form['chore-id']
        chore = Chore.query.get(chore_id)
        chore.name = request.form['chore-name']
        chore.frequency = FrequencyEnum(request.form['chore-frequency'])
        chore.times_per_frequency = request.form['chore-times']
        chore.duration_minutes = request.form['chore-duration']

        allocation_member_id = request.form['allocation']

        if allocation_member_id:
            allocated_user = AllocatedChore.query.filter_by(
                chore_id=chore_id).first()

            if not allocated_user:
                allocated_user = AllocatedChore(
                    household_member_id=allocation_member_id,
                    chore_id=chore_id,
                    due_date=datetime.now().date())  # Remove later
                db.session.add(allocated_user)

            allocated_user.household_member_id = allocation_member_id

        db.session.commit()
        flash(f"Chore #{chore_id} - '{chore.name.lower()}' \
            updated successfully!", 'success')
        return redirect(url_for('chore.manage'))

    chore = Chore.query.get(chore_id)
    members = household_helper.current_household().members
    return render_template('chores/edit-chore.html',
                           chore=chore,
                           members=members)


@bp.route('/manage/delete-chore/<int:chore_id>', methods=['GET', 'POST'])
@login_required
def delete_chore(chore_id):
    chore = Chore.query.get(chore_id)

    users_household = household_helper.current_household()

    if chore.household_id != users_household.id:
        flash("You do not have permission to delete this chore.", 'danger')
        return redirect(url_for('home.homepage'))

    if request.method == 'POST':
        db.session.delete(chore)
        db.session.commit()
        flash(f"Chore #{chore_id} - '{chore.name.lower()}' \
            deleted successfully!", 'success')
        return redirect(url_for('chore.manage'))

    return render_template('chores/delete-chore.html', chore=chore)

chorerate/routes/household.py
from flask import render_template, request, redirect, \
    url_for, flash, jsonify, Blueprint
from flask_login import login_required, current_user
from chorerate import db

# Models
from chorerate.models.household import Household
from chorerate.models.household_member import HouseholdMember
from chorerate.models.registration_link import RegistrationLink
from chorerate.models.user import User

from chorerate.helpers.household_helpers import current_household
from chorerate.helpers.chore_allocation import allocate_chores

from chorerate.exceptions import ChoreAllocationException

import traceback

import secrets

bp = Blueprint('household', __name__)


@bp.route('/confirm-chore-allocation', methods=['GET', 'POST'])
@login_required
def run_chore_allocation():
    '''View to the run chore allocation'''

    if request.method == 'POST':
        try:
            allocate_chores(current_household().id)
            flash('Chores allocated successfully!', 'success')
            return redirect(url_for('chore.manage'))
        except ChoreAllocationException as e:
            flash(str(e), 'danger')
        except Exception:
            flash('Something went wrong allocating chores.', 'error')
            print(traceback.format_exc())

    household = current_household()
    return render_template('household/confirm-chore-allocation.html',
                           household=household)


@bp.route('/create-household', methods=['GET', 'POST'])
@login_required
def create_household():
    '''View for the create household page'''

    if request.method == 'POST':
        # Create a new household
        household_name = request.form['household-name']
        new_household = Household(name=household_name)
        db.session.add(new_household)
        db.session.commit()

        # Add the current user to the household as a household member
        new_household_member = HouseholdMember(household_id=new_household.id,
                                               user_id=current_user.id)
        db.session.add(new_household_member)
        db.session.commit()

        flash(f"Household '{household_name}' created successfully!", 'success')
        return redirect(url_for('home.homepage'))
    return render_template('household/create-household.html')


@bp.route('/add-household-members', methods=['GET', 'POST'])
@login_required
def manage_members():
    '''View for the add household members page'''
    household = db.session.query(Household)\
        .join(HouseholdMember)\
        .filter(HouseholdMember.user_id == current_user.id).first()

    if request.method == 'POST':
        username = request.form['username']

        user = User.query.filter_by(username=username).first()

        if user:
            if user == current_user:
                flash("You cannot add yourself to your own household.",
                      'danger')
                return redirect(url_for('household.manage_members'))
            if user in household.members:
                flash(f"User '{username}' is already a member "
                      + "of household '{household.name}'.", 'danger')
                return redirect(url_for('household.manage_members'))

            household_member = HouseholdMember(household_id=household.id,
                                               user_id=user.id)
            db.session.add(household_member)
            db.session.commit()
            flash(f"User '{username}' added to household '{
                  household.name}' successfully!", 'success')
        else:
            flash(f"User '{username}' does not exist.", 'danger')

    members = household.members

    return render_template('household/manage-household-members.html',
                           household_id=household.id,
                           members=members)


@bp.route('/get-registration-link', methods=['POST'])
@login_required
def get_registration_link():
    '''Create a registration link for the household'''
    data = request.get_json()
    household_id = data['household_id']

    registration_link_record = RegistrationLink.query.filter_by(
        household_id=household_id).first()

    if registration_link_record:
        if registration_link_record.has_expired():
            # Link has expired, continue to generate a new one
            db.session.delete(registration_link_record)
            db.session.commit()
        else:
            # Return existing link
            registration_link = url_for(
                'auth.register',
                token=registration_link_record.token,
                _external=True)
            return jsonify({'success': True,
                            'registration_link': registration_link})

    token = secrets.token_urlsafe(16)

    new_link = RegistrationLink(token=token, household_id=household_id)
    db.session.add(new_link)
    db.session.commit()

    # Take to user registration page
    registration_link = url_for('auth.register', token=token, _external=True)

    return jsonify({'success': True, 'registration_link': registration_link})

chorerate/templates/chores/delete-chore.html
{% extends 'base.html' %}

{% block title %}
    {{ super() }} - Delete chore
{% endblock %}

{% block content %}

<div id="page-header">
    <h1>Delete chore: {{ chore.name }}</h1>
</div>

<form class="form form--sm" method="POST">
    <input type="hidden" name="chore-id" value="{{ chore.id }}">

    <p class="text-center">Are you sure you want to delete this chore?</p>
    <br>

    <div class="dual-form-btn-container">
        <a href="{{ url_for('chore.edit_chore', chore_id=chore.id) }}" class="btn btn--form btn--muted">Cancel</a>
        <button type="submit" class="btn btn--form" id="delete-chore-btn">Delete chore</button>
    </div>
</form>

{% endblock %}

chorerate/templates/chores/edit-chore.html
{% extends 'base.html' %}

{% block title %}
    {{ super() }} - Edit chore
{% endblock %}

{% block content %}

<div id="page-header">
    <h1>Edit chore #{{ chore.id }}</h1>
</div>

<div id="edit-chore">
    <form class="form form--sm" method="POST">
        <input type="hidden" name="chore-id" value="{{ chore.id }}">

        <div class="form-group">
            <label for="chore-name">Name:</label>
            <input type="text" id="chore-name" name="chore-name" value="{{ chore.name }}" required>
        </div>

        <div class="form-group">
            <label for="chore-frequency">Frequency:</label>
            <select id="chore-frequency" name="chore-frequency" required>
                <option value="monthly" {% if chore.frequency.value == 'monthly' %}selected{% endif %}>Monthly</option>
                <option value="weekly" {% if chore.frequency.value == 'weekly' %}selected{% endif %}>Weekly</option>
                <option value="daily" {% if chore.frequency.value == 'daily' %}selected{% endif %}>Daily</option>
            </select>
        </div>

        <div class="form-group form-group--inline">
            <input type="number" min="1" max="28" name="chore-times" id="chore-times" value="{{ chore.times_per_frequency }}" required>
            <label for="chore-times"> per <span id="frequency">{{ chore.frequency.value }}</span></label>
        </div>

        <div class="form-group">
            <label for="chore-duration">Duration (minutes):</label>
            <input type="number" step="5" id="chore-duration" name="chore-duration" value="{{ chore.duration_minutes }}" required>
        </div>

        <div class="form-group">
            <label for="chore-allocation">allocation:</label>
            <select name="allocation" id="allocation">
                {% if not chore.allocation %}
                    <option value="" selected>Unallocated</option>
                {% endif %}
                {% for member in members %}
                    <option value="{{ member.id }}" {% if chore.allocation and chore.allocation.household_member.id == member.id %}selected{% endif %}>{{ member.user.username }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="dual-form-btn-container">
            <button type="submit" class="btn btn--form">Update chore</button>
            <a href="{{ url_for('chore.delete_chore', chore_id=chore.id) }}" id="delete-chore-btn" class="btn btn--form btn--muted">Delete chore</a>
        </div>
    </form>
</div>

{% endblock %}

chorerate/templates/chores/edit-ratings.html
{% extends 'base.html' %}

{% block title %}
    {{ super() }} - Edit ratings
{% endblock %}

{% block content %}
    <div id="page-header">
        <h1>Edit ratings</h1>
    </div>

    <div id="edit-ratings">
        <ul class="chore-list">
            {% for chore in rated_chores %}
            <li>
                <span>
                    {{ chore.name }} 
                    <small>({{ chore.duration_minutes }} mins)</small>
                </span>

                <div class="rate-btn-container" data-chore="{{ chore.id }}">
                    {% for i in range(1, 11) %}
                        <button class="rate-btn {% if chore.rating == i %}selected{% endif %}" data-rate="{{ i }}">{{ i }}</button>
                    {% endfor %}
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/edit-ratings.js') }}"></script>
{% endblock %}

chorerate/templates/chores/manage.html
{% extends 'base.html' %}

{% block title %}
{{ super() }} - Manage
{% endblock %}

{% block content %}
    <div id="page-header">
        <h1>Manage chores</h1>
    </div>

    <a href="{{ url_for('household.run_chore_allocation') }}" class="btn btn--form">Run chore allocation</a>

    <div id="add-chore">
        <h2>Add chore:</h2>
        <form class="form" id="add-chore-form" method="POST">
            <div class="form-group">
                <label for="chore-name">Name:</label>
                <input type="text" id="chore-name" name="chore-name" required>
            </div>

            <div class="form-group">
                <label for="chore-frequency">Frequency:</label>
                <select id="chore-frequency" name="chore-frequency" required>
                    <option value="monthly">Monthly</option>
                    <option value="weekly">Weekly</option>
                    <option value="daily" selected>Daily</option>
                </select>
            </div>

            <div class="form-group form-group--inline">
                <input type="number" min="1" max="28" name="chore-times" id="chore-times" value="1">
                <label for="chore-times"> per <span id="frequency">day</span></label>
            </div>

            <div class="form-group">
                <label for="chore-duration">Duration (minutes):</label>
                <input type="number" id="chore-duration" name="chore-duration" value="15" required>
            </div>

            <button type="submit" class="btn btn--form">Create chore</button>
        </form>
    </div>

    <h2>Chores:</h2>
    <table class="chore-table">
        <tr>
            <th>Name</th>
            <th>Allocation</th>
            <th>Frequency</th>
            <th>Actions</th>
        </tr>
        {% for chore in chores %}
        <tr>
            <td>
                {{ chore.name }}
            </td>
            <td>
                {% if chore.allocation %}
                {{ chore.allocation.household_member.user.username }}
                {% else %}
                <i>Unallocated</i>
                {% endif %}
            </td>
            <td>
                {{ chore.times_per_frequency }}x
                {% if chore.frequency.value == 'daily' %}
                per day
                {% elif chore.frequency.value == 'weekly' %}
                per week
                {% elif chore.frequency.value == 'monthly' %}
                per month
                {% endif %}

                {{ chore.duration_minutes }} minutes
            </td>
            <td>
                <a href="{{ url_for('chore.edit_chore', chore_id=chore.id) }}">Edit</a>
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/add-chore.js') }}"></script>
{% endblock %}

chorerate/templates/chores/rate-chores.html
{% extends 'base.html' %}

{% block title %}
    {{ super() }} - Rate chores
{% endblock %}

{% block content %}

    <div id="page-header">
        <h1>Rate Chores</h1>
    </div>

    {% if not has_chores %}
        <div class="text-center">
            <p>No chores to rate.</p>
            <a href="{{ url_for('chore.manage') }}"><small>Add chores in Manage Chores first.</small></a>
        </div>
    {% else %}
        <div id="rate-chores-container" class="hidden">
            <p class="text-center">
                <small><span id="chore-index">1</span> out of <span id="unrated-total"></span> unrated.</small>
            </p>
            <div id="chore">
                <p id="chore-name"></p>
                <p><span id="times-per-frequency">1</span>x per <span id="frequency">day</span></p>
            </div>
            <br>
            <div class="rate-btn-container">
                {% for i in range(1, 11) %}
                    <button class="rate-btn" data-rate="{{ i }}">{{ i }}</button>
                {% endfor %}
            </div>

            <button class="btn btn--form hidden" id="back-btn">Back</button>
        </div>

        <div id="loading-indicator">
            <p>Loading...</p>
        </div>

        <p id="message" class="hidden text-center">No more chores left to rate.</p>
    {% endif %}

{% endblock %}

{% block scripts %}
    {% if has_chores %}
        <script src="{{ url_for('static', filename='js/rate-chores.js') }}"></script>
    {% endif %}
{% endblock %}